//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBorrowSale
    {
        public int BorrowSId { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> BQuantity { get; set; }
        public Nullable<double> BRate { get; set; }
        public Nullable<double> Recieved { get; set; }
        public string Type { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProduct tblProduct1 { get; set; }
    }
}
