//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyInfo
    {
        public int CompId { get; set; }
        public string CompName { get; set; }
        public string CompMobile { get; set; }
        public string CompPhone { get; set; }
        public string CompAddress { get; set; }
        public byte[] CompLogo { get; set; }
    }
}
