//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachineReading
    {
        public int MReadingId { get; set; }
        public Nullable<double> StartReading { get; set; }
        public Nullable<double> EndingReading { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public Nullable<int> MachineId { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
