//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNetSale
    {
        public int SaleId { get; set; }
        public int PId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> SaleQuantity { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> PendingAmount { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
