//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPumpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public int PurchId { get; set; }
        public int SupId { get; set; }
        public int PId { get; set; }
        public string TankerNo { get; set; }
        public double PurchQuantity { get; set; }
        public double PurchPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> PurchDate { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
